#ifndef FTP_LWIPOPTS_H
#define FTP_LWIPOPTS_H

#define NO_SYS 1
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_TIMERS 1
#define MEM_ALIGNMENT 4
#define MEM_SIZE (12 * 1024)
#define MEM_LIBC_MALLOC 0
#define MEMP_MEM_MALLOC 0
#define MEM_USE_POOLS 0
#define MEMP_NUM_PBUF 8
#define PBUF_POOL_SIZE 8
#define PBUF_POOL_BUFSIZE 1536
#define MEMP_NUM_TCP_PCB 8
#define MEMP_NUM_TCP_PCB_LISTEN 2
#define MEMP_NUM_TCP_SEG 24
#define MEMP_NUM_SYS_TIMEOUT 4
#define LWIP_TCP 1
#define TCP_MSS 536
#define TCP_WND 2144
#define TCP_SND_BUF 2144
#define TCP_SND_QUEUELEN 16
#define TCP_QUEUE_OOSEQ 0
#define TCP_OVERSIZE 0
#define LWIP_ARP 1
#define ARP_TABLE_SIZE 4
#define ARP_QUEUEING 0
#define ETH_PAD_SIZE 0
#define LWIP_ETHERNET 1
#define LWIP_IPV4 1
#define LWIP_ICMP 1
#define IP_FORWARD 0
#define IP_FRAG 0
#define IP_REASSEMBLY 0
#define LWIP_IPV6 0
#define LWIP_UDP 0
#define LWIP_UDPLITE 0
#define LWIP_RAW 0
#define LWIP_DNS 0
#define LWIP_DHCP 0
#define LWIP_AUTOIP 0
#define LWIP_ACD 0
#define LWIP_IGMP 0
#define LWIP_ALTCP 0
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_NETIF_API 0
#define LWIP_NETIF_HOSTNAME 0
#define LWIP_NETIF_LOOPBACK 0
#define LWIP_STATS 1
#define LWIP_STATS_DISPLAY 0
#define MEM_STATS 1
#define MEMP_STATS 1
#define LINK_STATS 1
#define ETHARP_STATS 1
#define IP_STATS 1
#define ICMP_STATS 1
#define TCP_STATS 1
#define SYS_STATS 0
#define LWIP_DEBUG 0

#endif
