/* Offline native SDK ABI tests. Never opens BPF or accesses an interface. */
#include <assert.h>
#include <net/bpf.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "../host/ethernet_raw_capture.h"
#include "../../../../examples/ethernet-raw/raw_protocol.h"

static const uint8_t host[6] = {0, 0x11, 0x22, 0x33, 0x44, 0x55};
static const raw_message_t expected = {
    .sequence = 0x12345678u,
    .nonce = {0xFE, 0xDC, 0xBA, 0x98, 0x76, 0x54, 0x32, 0x10}
};
static const uint8_t golden[RAW_FRAME_BYTES] = {
    0,0x11,0x22,0x33,0x44,0x55, 2,0,0,0x69,0x65,2,
    0x88,0xB5, 'L','M','3','S','R','A','W','1', 1,2,
    0x12,0x34,0x56,0x78, 0xFE,0xDC,0xBA,0x98,0x76,0x54,0x32,0x10,
    0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
};

static size_t record(uint8_t *out, size_t hlen, const uint8_t *frame)
{
    struct bpf_hdr header = {0};
    header.bh_hdrlen = (u_short)hlen;
    header.bh_caplen = RAW_FRAME_BYTES;
    header.bh_datalen = RAW_FRAME_BYTES;
    const size_t size = BPF_WORDALIGN(hlen + RAW_FRAME_BYTES);
    memset(out, 0, size);
    memcpy(out, &header, sizeof header);
    memcpy(out + hlen, frame, RAW_FRAME_BYTES);
    return size;
}

static void check(const uint8_t *data, size_t size, bool valid, bool match)
{
    bool matched = true;
    assert(raw_capture_match(data, size, host, &expected, &matched) == valid);
    assert(matched == match);
}

/* Interpreter for only the three instruction forms generated by our filter.
 * Uses SDK instructions, network-order loads, forward jumps and OOB rejection.
 * Not a substitute for live kernel validation. */
static uint32_t filter_result(const struct bpf_insn *code,
                              const uint8_t *frame, size_t size)
{
    uint32_t accumulator = 0u;
    for (size_t pc = 0u; pc < RAW_FILTER_INSNS; ++pc)
    {
        const struct bpf_insn instruction = code[pc];
        switch (instruction.code)
        {
            case BPF_LD | BPF_W | BPF_LEN:
                accumulator = (uint32_t)size;
                break;
            case BPF_LD | BPF_W | BPF_ABS:
            {
                const size_t p = instruction.k;
                if (p > size || size - p < 4u) { return 0u; }
                accumulator = ((uint32_t)frame[p] << 24) |
                    ((uint32_t)frame[p + 1u] << 16) |
                    ((uint32_t)frame[p + 2u] << 8) | frame[p + 3u];
                break;
            }
            case BPF_JMP | BPF_JEQ | BPF_K:
                pc += accumulator == instruction.k ?
                    instruction.jt : instruction.jf;
                assert(pc < RAW_FILTER_INSNS);
                break;
            case BPF_RET | BPF_K: return instruction.k;
            default: assert(false);
        }
    }
    assert(false);
    return 0u;
}

int main(void)
{
    uint8_t request[RAW_FRAME_BYTES], reply[RAW_FRAME_BYTES];
    assert(raw_build_request(request, sizeof request, host, expected.sequence,
                             expected.nonce));
    assert(raw_build_reply(request, sizeof request, reply, sizeof reply));
    assert(memcmp(reply, golden, sizeof golden) == 0);
    struct bpf_insn filter[RAW_FILTER_INSNS];
    raw_reply_filter(filter, golden);
    assert(filter_result(filter, golden, sizeof golden) ==
           RAW_FRAME_BYTES);
    assert(filter_result(filter, request, sizeof request) == 0u);
    uint8_t storage[1024], bad[RAW_FRAME_BYTES];
    for (size_t alignment = 0u; alignment < 4u; ++alignment)
    {
        uint8_t *data = storage + alignment;
        /* Native Ethernet bh_hdrlen can omit trailing C struct padding. */
        const size_t fields = offsetof(struct bpf_hdr, bh_hdrlen) +
            sizeof(((struct bpf_hdr *)0)->bh_hdrlen);
        for (size_t hlen = fields; hlen < sizeof(struct bpf_hdr) + 8u; ++hlen)
        {
            const size_t size = record(data, hlen, golden);
            check(data, size, true, true);
            check(data, hlen + RAW_FRAME_BYTES, true, true);
            for (size_t n = 1u; n < hlen + RAW_FRAME_BYTES; ++n)
            {
                check(data, n, false, false);
            }
            /* Complete request plus reply, with inter-record alignment. */
            const size_t first = record(data, hlen, request);
            const size_t second = record(data + first, hlen, golden);
            check(data, first + second, true, true);
            check(data, first, true, false); /* outgoing never matches */
            check(data, first + second + 1u, false, false);
        }
    }
    check(NULL, 0u, true, false);
    for (size_t byte = 0u; byte < RAW_FRAME_BYTES; ++byte)
    {
        memcpy(bad, golden, sizeof bad);
        /* Wrong nonce, sequence, MAC, and every payload byte. */
        bad[byte] ^= 1u;
        const size_t size = record(storage, sizeof(struct bpf_hdr), bad);
        check(storage, size, true, false);
        assert(filter_result(filter, bad, sizeof bad) == 0u);
    }
    for (size_t n = 0u; n < RAW_FRAME_BYTES; ++n)
    {
        assert(filter_result(filter, golden, n) == 0u);
    }
    uint8_t longer[64] = {0};
    memcpy(longer, golden, sizeof golden);
    assert(filter_result(filter, longer, sizeof longer) == 0u);
    /* Header corruption: undersize/oversize, integer extremes, truncation. */
    const uint32_t lengths[] = {0u, 1u, 59u, 60u, 61u, UINT32_MAX};
    for (size_t c = 0u; c < sizeof lengths / sizeof lengths[0]; ++c)
    {
        for (size_t d = 0u; d < sizeof lengths / sizeof lengths[0]; ++d)
        {
            const size_t size = record(storage, sizeof(struct bpf_hdr), golden);
            struct bpf_hdr header;
            memcpy(&header, storage, sizeof header);
            header.bh_caplen = lengths[c];
            header.bh_datalen = lengths[d];
            memcpy(storage, &header, sizeof header);
            bool matched;
            const bool valid = raw_capture_match(storage, size, host,
                                                  &expected, &matched);
            assert(!matched || (valid && lengths[c] == 60u &&
                                lengths[d] == 60u));
            if (lengths[c] > 60u || lengths[c] > lengths[d]) { assert(!valid); }
        }
    }
    const u_short headers[] = {0u, 1u, 17u, 81u, UINT16_MAX};
    for (size_t i = 0u; i < sizeof headers / sizeof headers[0]; ++i)
    {
        const size_t size = record(storage, sizeof(struct bpf_hdr), golden);
        struct bpf_hdr header;
        memcpy(&header, storage, sizeof header);
        header.bh_hdrlen = headers[i];
        memcpy(storage, &header, sizeof header);
        check(storage, size, false, false);
    }
    /* Matching reply followed by malformed record must not produce a pass. */
    const size_t size = record(storage, sizeof(struct bpf_hdr), golden);
    memset(storage + size, 0, sizeof(struct bpf_hdr));
    check(storage, size + sizeof(struct bpf_hdr), false, false);
    /* Deterministic arbitrary byte buffers under sanitizers; no OS access. */
    uint32_t random = 1u;
    for (size_t n = 0u; n < 10000u; ++n)
    {
        for (size_t i = 0u; i < sizeof storage; ++i)
        {
            random = random * 1664525u + 1013904223u;
            storage[i] = (uint8_t)(random >> 24);
        }
        bool matched;
        (void)raw_capture_match(storage, n % sizeof storage, host,
                                &expected, &matched);
        assert(!matched);
    }
    printf("Offline native BPF tests passed (sizeof bpf_hdr=%zu).\n",
           sizeof(struct bpf_hdr));
    puts("No BPF opened; no capture/injection; no fresh physical claim.");
    return 0;
}
